version: '3.8'

services:
  angular-app:
    build:
      context: .
      dockerfile: Dockerfile  # Pfad zur Dockerfile, falls sie nicht im Hauptverzeichnis liegt
    ports:
      - "4200:4200"  # Bindet Port 4200 des Containers an Port 4200 des Hosts
    volumes:
      - ./IAMCalculator:/usr/src/app  # Bindet den Code der Angular-App in den Container
      - /usr/src/app/node_modules  # Verhindert, dass node_modules überschrieben wird
    environment:
      - CHOKIDAR_USEPOLLING=true  # Ermöglicht das Überwachen von Dateiänderungen (z.B. für Angular-CLI)
    command: ["ng", "serve", "--host", "0.0.0.0", "--disable-host-check"]
