services:

  mongodb:
    image: mongo
    container_name: mongodb-container_backend
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=secret
      - MONGO_INITDB_DATABASE=IAMCalculator
    restart: always

  backend:
    image: iambackend:latest
    container_name: node-backend
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
    environment:
      - MONGO_URI=mongodb://mongodb-container_backend:27017/IAMCalculator?authSource=admin
    volumes:
      - ./IAMCalculatorV2_Backend/server.js:/app/server.js
    command: /bin/bash -c "npm install && node server.js"
    restart: always

    
  angular-app:
    image: iamcalculator:latest
    ports:
      - "80:80"
    volumes:
      - ./IAMCalculator:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: ["ng", "serve", "--host", "0.0.0.0", "--disable-host-check"]
    restart: always

volumes:
  mongo-data: